#!/bin/bash 

source ~/.ec2auto

if (( $# != 1 ))
then
  echo "ecssh - open SSH connection to Amazon EC2 instance"
  echo
  echo "Usage: ecssh <instance-id>"
  echo
  exit 1
fi

if [ -z "$EC2_KEY_FILE" ]; then
  echo 'Error: $EC2_KEY_FILE not set'
  exit 2
fi

ID=$1
EXISTS=`ec2dins --region $EC2_REGION $ID 2>/dev/null | wc -l`

if [ "$EXISTS" -eq "0" ]
then
  echo "can't find instance $ID"
  exit 3
fi

IP=`ec2-describe-instances --region $EC2_REGION $ID | grep INSTANCE | awk '{print $14}'`

EC_SSH_USER=""
if [ -z "$EC2_INSTANCE_USER" ]; then
 EC_SSH_USER="ubuntu" # default user for AWS instance
else
 EC_SSH_USER=$EC2_INSTANCE_USER
fi

ssh -i $EC2_KEY_FILE $EC_SSH_USER@$IP
